######################################################################
# Automatically generated by qmake (3.0) mar. janv. 23 00:47:56 2018
######################################################################

QT=testlib
TEMPLATE = app
TARGET = Tests
INCLUDEPATH += .

# Input
HEADERS += testsManager.h
SOURCES += testsManager.cpp
